import { Suspense } from 'react'

export const metadata = {
	title: 'Next.js',
	description: 'Generated by Next.js',
}

export default function DashboardLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<>
			<Suspense>
				<header>Dashboard Header</header>
			</Suspense>
			<main className='min-h-screen'>
				{children}
			</main>
		</>
	)
}
